# API Check Configuration

[server]
host = "127.0.0.1"
port = 3000

[proxy]
enabled = false
# target = "http://localhost:8080"

[test]
num_calls = 10
frequency_ms = 100
method = "GET"
# target_url = "http://localhost:3000/test"
# body = '{"key": "value"}'
# headers = [["Content-Type", "application/json"]]
